### PR TITLE
eslint and coverage

### PR DESCRIPTION
**Pull request by VladVega**
adds coverage and eslint: https://github.com/juttle/juttle-postgres-adapter/issues/20

### CODE REVIEW

**Comment by VladVega** [comment]
@davidvgalbraith @dmehra

**Comment by davidvgalbraith** [comment]
+1

**Comment by dmehra** [comment]
+1
coverage a bit low on branches, you'll look at what's lacking, right @VladVega ?

**Comment by VladVega** [comment]
@dmehra I totally agree. Just let me get these in and I'll leave your issues open to actually look at and bring up test coverage and thresholds.

**Pull request merged**
